<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB4wevQs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB4wevQs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB4wevQs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB4wevQs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB4wevQs\App_KernelDevDebugContainer([
    'container.build_hash' => 'B4wevQs',
    'container.build_id' => '666b81b9',
    'container.build_time' => 1759057239,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB4wevQs');
